name: Build + Auto-Approve

on: 
    pull_request:

permissions:
  pull-requests: write
  contents: write
jobs:

  production-build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
    strategy:
        matrix:
          node-version: [22, 24, 26]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name : Install + Build
        run: |
            npm install -g @angular/cli
            cd app
            npm install
            npm run production

  auto-approve:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate-token.outputs.token }}
    permissions:
      pull-requests: write
      contents: write
    needs: production-build
    if: needs.production-build.result == 'success' && github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: |
            ${{ secrets.PRIVATE_KEY }}
      - name: Auto Approve
        run: gh pr review --approve "$PR_URL" --body "Auto-approving PR as production build passed."
        env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GH_TOKEN: ${{ steps.generate-token.outputs.token }}
  merge:
    runs-on: ubuntu-latest
    needs: [auto-approve, production-build]
    permissions:
      pull-requests: write
      contents: write
    if: needs.auto-approve.result == 'success' && github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: |
            ${{ secrets.PRIVATE_KEY }}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}