name: Docker Compose Up

on:
    push:

jobs:

    compose-up:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
                sudo curl -L "https://github.com/docker/compose/releases/download/2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose

            - name: Docker compose up
              run: |
                docker compose up -d
                sleep 60
                docker compose down
