name: Docker Compose Up

on:
    push:

jobs:

    compose-up:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up node
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install docker compose
              run: sudo apt-get install docker-compose-plugin

            - name: Docker compose up
              run: docker compose up